#!/bin/bash

#This script use ssh and connect with the computer that passed through first param
#Then when connection has established, use whereis and the second param to find the program

ssh jt@159.90.9.$1  whereis $2
